#!/usr/bin/env bash

CURCWD=$(pwd -P)
MYCWD="$(dirname "$0")"
PHPXSXML="wordpress"
PHPXSXML_FORCE=no
PHPXSXML_SOURCE=""
PHPXSXML_TMP=""

if [ ! -d "${MYCWD}/vendor" ]; then
	pushd "$MYCWD"
	composer install
	popd
fi

VERSION=8

if [ "compat" = "$1" ]; then
	PHPXSXML="PHPCompatibility"
	PHPXSXML_FORCE=yes
	shift
	[ "$1" = "-v" ] && VERSION=$2 && shift && shift

	echo "Running PHP Compatibility check with PHP version $VERSION"
fi

BREW_PRESENT=yes
[ "" = "$(which brew)" ] && BREW_PRESENT=no

ORGPATH="$PATH"
#
#if [ "PHP 8" = "$(php --version | egrep -o 'PHP\ 8')" ]; then
#	if [ "no" = "$BREW_PRESENT" ]; then
#		echo "PHP 8.x is currently installed and HomeBrew is not available to provide an alternative."
#		echo "PHPCS is NOT compatible with PHP 8.x."
#		echo "Cannot continue."
#		exit 2;
#	else
#		PHP_PATH=$(brew list php@7.4 | egrep '/bin/php$')
#		if [ "" != "$PHP_PATH" ]; then
#			PHP_PATH=$(dirname "$PHP_PATH")
#			export PATH="$PHP_PATH/:$PATH"
#		else
#			echo "PHP 8.x is currently linked, and PHP 7.4 is not found."
#			echo "PHPCS is NOT compatible with PHP 8.x."
#			echo "Please install and link php@7.4:      brew install php@7.4 "
#			echo "And optionally link as default PHP:   brew unlink php ; brew link php@7.4"
#			exit 1;
#		fi
#	fi
#fi

PARAM=$1

if [ "watch" = "$PARAM" ]; then
	shift
	if [ "" = "$(which watch)" ]; then
		if [ "no" = "$BREW_PRESENT" ]; then
			echo "HomeBrew not available, ignoring 'watch'"
			PARAM=""
		else
			brew install watch
		fi
	fi
fi

if [ "fix" = "$PARAM" ]; then
	shift;
fi

[ -f "phpcs.xml" ] && PHPXSXML_SOURCE="${CURCWD}/phpcs.xml"
[ -f "phpcs.xml.dist" ] && PHPXSXML_SOURCE="${CURCWD}/phpcs.xml.dist"

[ "yes" = "$PHPXSXML_FORCE" ] && PHPXSXML_SOURCE=""

if [ "" != "$PHPXSXML_SOURCE" ]; then
	PHPXSXML_TMP="${CURCWD}/phpcs.xml.phpcs".$$
	cp "$PHPXSXML_SOURCE" "$PHPXSXML_TMP"
	# Remove this as we already do this and this line will cause errors.
	cat "$PHPXSXML_TMP" | sed 's@<rule ref="PHPCompatibilityWP"/>@@' | sed -E 's@<exclude-pattern>[^<]+\.js</exclude-pattern>@@' > "$PHPXSXML_SOURCE"
	PHPXSXML="$PHPXSXML_SOURCE"
fi

cd "$(dirname "$0")"

TO_SCAN="$1"
[ "$TO_SCAN" = "" ] && TO_SCAN="$CURCWD"
[ ! -e "$TO_SCAN" ] && [ -e "$CURCWD/$TO_SCAN" ] && TO_SCAN="$CURCWD/$TO_SCAN"

if [ "fix" = "$PARAM" ]; then
	./vendor/bin/phpcbf --standard="$PHPXSXML" --runtime-set testVersion $VERSION --extensions=php -psd memory_limit=1G  --ignore=vendor --ignore=node_modules "$TO_SCAN"
elif [ "watch" = "$PARAM" ]; then
	watch ./vendor/bin/phpcs --standard='"'$PHPXSXML'"' --runtime-set testVersion $VERSION --extensions=php -sd memory_limit=1G  --ignore=vendor --ignore=node_modules '"'$TO_SCAN'"'
else
	./vendor/bin/phpcs --standard="$PHPXSXML" --runtime-set testVersion $VERSION --extensions=php -psd memory_limit=1G  --ignore=vendor --ignore=node_modules "$TO_SCAN"
fi

if [ -f "$PHPXSXML_TMP" ]; then
	mv "$PHPXSXML_TMP" "$PHPXSXML_SOURCE"
fi

export PATH="$ORGPATH"
