#!/usr/bin/env bash

CURCWD=$(pwd -P)
MYCWD="$(dirname "$0")"
PHPXSXML="wordpress"
PHPXSXML_SOURCE=""
PHPXSXML_TMP=""

if [ ! -d "${MYCWD}/vendor" ]; then
	pushd "$MYCWD"
	composer install
	popd
fi

BREW_PRESENT=yes
[ "" = "$(which brew)" ] && BREW_PRESENT=no

ORGPATH="$PATH"

PARAM=$1

if [ "watch" = "$PARAM" ]; then
	shift
	if [ "" = "$(which watch)" ]; then
		if [ "no" = "$BREW_PRESENT" ]; then
			echo "HomeBrew not available, ignoring 'watch'"
			PARAM=""
		else
			brew install watch
		fi
	fi
fi

if [ "fix" = "$PARAM" ]; then
	shift;
fi

[ -f "phpcs.xml" ] && PHPXSXML_SOURCE="${CURCWD}/phpcs.xml"
[ -f "phpcs.xml.dist" ] && PHPXSXML_SOURCE="${CURCWD}/phpcs.xml.dist"

if [ "" != "$PHPXSXML_SOURCE" ]; then
	PHPXSXML_TMP="${CURCWD}/phpcs.xml.phpcw".$$
	# Add lines to the file to upgrade the sniffs. Any line with the following list of sniff names will be duplicated and the duplicate will have the new sniff name.
    # Generic.Arrays.DisallowShortArraySyntax.Found => Universal.Arrays.DisallowShortArraySyntax.Found
    if grep -q "Universal.Arrays.DisallowShortArraySyntax.Found" "$PHPXSXML_SOURCE"; then
        # do nothing
        true
    else
        sed -i '' '/Generic.Arrays.DisallowShortArraySyntax.Found/ {p; s/Generic.Arrays.DisallowShortArraySyntax.Found/Universal.Arrays.DisallowShortArraySyntax.Found/ ;}' "$PHPXSXML_SOURCE"
    fi
    # WordPress.PHP.DisallowShortTernary.Found => Universal.Operators.DisallowShortTernary.Found
    if grep -q "Universal.Operators.DisallowShortTernary.Found" "$PHPXSXML_SOURCE"; then
        # do nothing
        true
    else
        sed -i '' '/WordPress.PHP.DisallowShortTernary.Found/ {p; s/WordPress.PHP.DisallowShortTernary.Found/Universal.Operators.DisallowShortTernary.Found/ ;}' "$PHPXSXML_SOURCE"
    fi

	cp "$PHPXSXML_SOURCE" "$PHPXSXML_TMP"
	# Remove this as we already do this and this line will cause errors.
	cat "$PHPXSXML_TMP" | sed 's@<rule ref="PHPCompatibilityWP"/>@@' > "$PHPXSXML_SOURCE"
	PHPXSXML="$PHPXSXML_SOURCE"
fi

cd "$(dirname "$0")"

TO_SCAN="$1"
[ "$TO_SCAN" = "" ] && TO_SCAN="$CURCWD"
[ ! -e "$TO_SCAN" ] && [ -e "$CURCWD/$TO_SCAN" ] && TO_SCAN="$CURCWD/$TO_SCAN"

if [ "fix" = "$PARAM" ]; then
	./vendor/bin/phpcbf --standard="$PHPXSXML" --extensions=php -psd memory_limit=1G  --ignore=vendor --ignore=node_modules "$TO_SCAN"
elif [ "watch" = "$PARAM" ]; then
	watch ./vendor/bin/phpcs --standard='"'$PHPXSXML'"' --extensions=php -sd memory_limit=1G  --ignore=vendor --ignore=node_modules '"'$TO_SCAN'"'
else
	./vendor/bin/phpcs --standard="$PHPXSXML" --extensions=php -psd memory_limit=1G  --ignore=vendor --ignore=node_modules "$TO_SCAN"
fi

if [ -f "$PHPXSXML_TMP" ]; then
	mv "$PHPXSXML_TMP" "$PHPXSXML_SOURCE"
fi

export PATH="$ORGPATH"
