#!/usr/bin/env bash

# Resolve $0 through any symlinks so we find the phpcw that lives next to this script.
SELF="$0"
while [ -L "$SELF" ]; do
	LINK="$(readlink "$SELF")"
	case "$LINK" in
		/*) SELF="$LINK" ;;
		*) SELF="$(dirname "$SELF")/$LINK" ;;
	esac
done

"$(dirname "$SELF")"/phpcw fix "$@"