#!/usr/bin/env bash

CURCWD=$(pwd -P)

# Resolve $0 through any symlinks (e.g. ~/.local/bin/phpcw -> this repo) so MYCWD is the real installation dir.
SELF="$0"
while [ -L "$SELF" ]; do
	LINK="$(readlink "$SELF")"
	case "$LINK" in
		/*) SELF="$LINK" ;;
		*) SELF="$(dirname "$SELF")/$LINK" ;;
	esac
done
MYCWD="$(cd "$(dirname "$SELF")" && pwd -P)"
PHPXSXML="wordpress"
PHPXSXML_SOURCE=""
PHPXSXML_TMP=""

if [ ! -d "${MYCWD}/vendor" ]; then
	pushd "$MYCWD"
	composer install
	popd
fi

# Poor-man's updater; checks for updates once a week. Disable with PHPCW_NO_UPDATE_CHECK=1.
[ -f "${MYCWD}/update-check.sh" ] && . "${MYCWD}/update-check.sh" && phpcw_update_check

BREW_PRESENT=yes
[ "" = "$(which brew)" ] && BREW_PRESENT=no

ORGPATH="$PATH"

PARAM=$1

if [ "watch" = "$PARAM" ]; then
	shift
	if [ "" = "$(which watch)" ]; then
		if [ "no" = "$BREW_PRESENT" ]; then
			echo "HomeBrew not available, ignoring 'watch'"
			PARAM=""
		else
			brew install watch
		fi
	fi
fi

if [ "fix" = "$PARAM" ]; then
	shift;
fi

PHPXSXML_TMP=""
phpcw_cleanup() {
	if [ ! -z $PHPXSXML_TMP ] && [ -f "$PHPXSXML_TMP" ]; then
		mv "$PHPXSXML_TMP" "$PHPXSXML_SOURCE"
	fi
}

trap phpcw_cleanup SIGINT
trap phpcw_cleanup exit

[ -f "phpcs.xml" ] && PHPXSXML_SOURCE="${CURCWD}/phpcs.xml"
[ -f "phpcs.xml.dist" ] && PHPXSXML_SOURCE="${CURCWD}/phpcs.xml.dist"

if [ "" != "$PHPXSXML_SOURCE" ]; then
	PHPXSXML_TMP="${CURCWD}/phpcs.xml.phpcw".$$
	# Add lines to the file to upgrade the sniffs. Any line with the following list of sniff names will be duplicated and the duplicate will have the new sniff name.
    # Generic.Arrays.DisallowShortArraySyntax.Found => Universal.Arrays.DisallowShortArraySyntax.Found
    if grep -q "Universal.Arrays.DisallowShortArraySyntax.Found" "$PHPXSXML_SOURCE"; then
        # do nothing
        true
    else
        sed -i '' '/Generic.Arrays.DisallowShortArraySyntax.Found/ {p; s/Generic.Arrays.DisallowShortArraySyntax.Found/Universal.Arrays.DisallowShortArraySyntax.Found/ ;}' "$PHPXSXML_SOURCE"
    fi
    # WordPress.PHP.DisallowShortTernary.Found => Universal.Operators.DisallowShortTernary.Found
    if grep -q "Universal.Operators.DisallowShortTernary.Found" "$PHPXSXML_SOURCE"; then
        # do nothing
        true
    else
        sed -i '' '/WordPress.PHP.DisallowShortTernary.Found/ {p; s/WordPress.PHP.DisallowShortTernary.Found/Universal.Operators.DisallowShortTernary.Found/ ;}' "$PHPXSXML_SOURCE"
    fi

	cp "$PHPXSXML_SOURCE" "$PHPXSXML_TMP"
	# Remove this as we already do this and this line will cause errors.
	cat "$PHPXSXML_TMP" | sed 's@<rule ref="PHPCompatibilityWP"/>@@' | sed -E 's@<exclude-pattern>[^<]+\.js</exclude-pattern>@@' > "$PHPXSXML_SOURCE"
	PHPXSXML="$PHPXSXML_SOURCE"
fi

cd "$MYCWD"

TO_SCAN=()
for ARG in "$@"; do
	[ -z "$ARG" ] && ARG="$CURCWD"
	[ ! -e "$ARG" ] && [ -e "$CURCWD/$ARG" ] && ARG="$CURCWD/$ARG"
	[ -e "$ARG" ] && TO_SCAN+=("$ARG")
done
[ ${#TO_SCAN[@]} -eq 0 ] && TO_SCAN+=("$CURCWD")


if [ "fix" = "$PARAM" ]; then
	./vendor/bin/phpcbf --standard="$PHPXSXML" --extensions=php -psd memory_limit=1G  --ignore=vendor --ignore=node_modules "${TO_SCAN[@]}"
elif [ "watch" = "$PARAM" ]; then
	watch --color ./vendor/bin/phpcs --standard='"'$PHPXSXML'"' --extensions=php -sd memory_limit=1G  --ignore=vendor --ignore=node_modules $(printf '"%s" ' "${TO_SCAN[@]}")
else
	./vendor/bin/phpcs --standard="$PHPXSXML" --extensions=php -psd memory_limit=1G  --ignore=vendor --ignore=node_modules "${TO_SCAN[@]}"
fi

# phpcw_cleanup

export PATH="$ORGPATH"
